### ISSUE TITLE
Unable to write proper xpath with matches keyword in an xpath (for case insensitive xpath creation)

### ISSUE THREAD

**Issue by rizwanaabdulkalam** [SelectorsHub/SelectorsHubIssues#12]
Hi Sanjay,

Please follow the below steps:
Open a website > Write an xpath with matches keyword in order to find a button with a particular text as case insensitive (eg: //*[matches(text(),'List players')]) > While writing this in selectors hub, error is shown as 'after / only . * and tagname allowed'

I am not able to understand what error this is. I think this is not the correct error message. Please find attached the screenshot of the error message displayed
![image](https://user-images.githubusercontent.com/74894825/99935118-f046bc80-2d85-11eb-8af9-3ce47b805e0d.png)

I am actually not sure how to write an xpath with matches keyword (in order to make xpath case insensitive). It will be helpful if you could include support for this.

Thanks,
Rizwana

PS: This is a great tool because it gives suggestions. Very innovative idea. Keep going. All the best 👍

**Comment by selectorshubsanjay** [comment]
Thank you Rizwan for the detailed info. Sure I will help you here.
'matches' is not the correct keyword for xpath. You should use 'contains' keyword.
For ex- //div[contains(text(),'List players')]

And also avoid using *, use tagname.

Sure, i will improve the error message so that it will give correct information in this case.
