### ISSUE TITLE
Wrong error message is shown for invalid xpath

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#20]
I type normalise instead of normalize 

The error i got was confusing. If it can be corrected user will find it easy

site name is automation practise.com and button is create account which comes after clicking on sign in 

![image](https://user-images.githubusercontent.com/15048211/110938062-4d787500-8359-11eb-866f-a7ed07052c88.png)

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for highlighting this issue and sharing the detailed info.
I will fix this soon in next release. Appreciate your support.

**Comment by selectorshubsanjay** [comment]
Hi Gaurav, this issue is fixed now and it is live in chrome store with the version 3.0.1.
Now the error message will be proper as shown in this image.
Kindly let me know if there any further improvements required. 

![image](https://user-images.githubusercontent.com/67390539/111522274-1c94a780-8780-11eb-96a8-a10cb3f78a68.png)

**Comment by gauravkhuraana** [comment]
![image](https://user-images.githubusercontent.com/15048211/112143552-082c3100-8bfe-11eb-8963-9327acf38e9e.png)

Thanks Sanjay for taking this on priority and making it a feature 
Its awesome again now
