### ISSUE TITLE
Toggling the case insensitivity button on and off does not work

### ISSUE THREAD

**Issue by sankalprao** [SelectorsHub/SelectorsHubIssues#27]
**Steps to Reproduce:**

1. Open browser with SelectorsHub installed.
2. Inspect any element on a web page
3. Once you are able to get the locator suggestions ins SelectorsHub, click on the case insensitive button to turn it on.
4. Now notice that the relative xpath option changes to insensitive one Example: //nav[translate(@aria-label, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')='repository']
5. Now clicking back on the same button should turn this feature off and then it should again be converted to case sensitive one
   without the user having to inspect again.

Note: 1)  I am not sure if this feature is supposed to turn on and off again and regenerate the xpath locator suggestion again. If this is not a feature designed, I would request for an enhancement as user would not like to inspect the element again.

2. Is it possible to generate case sensitive xpath locator using regex For ex : 
 //nav[translate(@aria-label, '[A-Z]', '[a-z]')='repository'] something like this

Please see the attached gif to understand the issue:

![ToggleCaseSensitivity](https://user-images.githubusercontent.com/36331783/114526621-82deee00-9c8a-11eb-9fb4-2b4d207959c8.gif)

**Comment by selectorshubsanjay** [comment]
Thank you Sankalp for great suggestions.
Actually you got it right, this feature was designed in such a way that whenever user want to convert a generated selector to case insensitive selector they can just simply click on that button and make it and it was not a toggle button earlier.

I liked your suggestion and now made it as a toggle button. So whenever you want to convert generated selector as case insensitive, just click on that and to convert back to default again click on the same button.

Note: Regex is not supported in XPath 1, regex are supported in XPath 2 but the problem is XPath is not yet supported by chrome so for now we will have to live with it. I am trying figure out more ways, if it will be possible definitely will implement that feature. Also if you get any more idea on that please let me know. Thank you.


https://user-images.githubusercontent.com/67390539/114548124-f7129500-9c7c-11eb-9992-1326157866b6.mov

**Comment by selectorshubsanjay** [comment]
This feature is live now with 3.0.8 release. Please verify it. Thank you.
