### ISSUE TITLE
Test case studio asking for install even when its already installed

### ISSUE THREAD

**Issue by HaggaiBrian** [SelectorsHub/SelectorsHubIssues#38]
Been using test case studio but suddenly today it work but keeps as asking for install. Reinstall is done, a couple of restarts to both browser and laptop later, still asking for install

Expected behavior : Clicking test case studio should lauch test case studio
Actual Behaviour : Clicking test case studio navigates to install page in chrom extension store

Reproducible : Yes
Browser : Chrome

**Comment by selectorshubsanjay** [comment]
Thank you for highlighting this and sharing the details.
Actually I have separated the TestCase Studio from SelectorsHub and launched it as a separate plugin so that is the reason it is opening the install page on clicking on TestCase Studio icon.
Please follow this tutorial to learn more about it.
https://www.youtube.com/watch?v=rYDcfC2mjuk
